development:
  adapter: postgresql
  encoding: unicode
  database: meetups_development
  pool: 20
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: meetups_test
  pool: 20
  username:
  password:
